games = [
    dict(
        id="1",
        title="Game 1",
        description="Description 1",
        min_players=2,
        max_players=6,
        min_ideal_players=3,
        max_ideal_players=6,
        min_play_time=60,
        max_play_time=2 * 60,
        rule_time=20,
        complexity="hard",
        min_age=18,
        year=2018,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["adventure"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/pandemic_legacy_season_1/650787/conversions/pic2452831-thumb.jpg",
    ),
    dict(
        id="2",
        title="Game 2",
        description="Description 2",
        min_players=1,
        max_players=4,
        min_ideal_players=2,
        max_ideal_players=4,
        min_play_time=30,
        max_play_time=90,
        rule_time=10,
        complexity="medium",
        min_age=12,
        year=2020,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["strategy"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/the_mandalorian_adventures/921597/conversions/pic8172090-thumb.jpg",
    ),
    dict(
        id="3",
        title="Game 3",
        description="Description 3",
        min_players=3,
        max_players=8,
        min_ideal_players=4,
        max_ideal_players=7,
        min_play_time=45,
        max_play_time=120,
        rule_time=15,
        complexity="easy",
        min_age=10,
        year=2019,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["fantasy"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/the_mandalorian_adventures/921597/conversions/pic8172090-thumb.jpg",
    ),
    dict(
        id="4",
        title="Game 4",
        description="Description 4",
        min_players=2,
        max_players=5,
        min_ideal_players=3,
        max_ideal_players=5,
        min_play_time=75,
        max_play_time=150,
        rule_time=25,
        complexity="hard",
        min_age=16,
        year=2017,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["horror"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/pandemic_legacy_season_1/650787/conversions/pic2452831-thumb.jpg",
    ),
    dict(
        id="5",
        title="Game 5",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/the_mandalorian_adventures/921597/conversions/pic8172090-thumb.jpg",
    ),
    dict(
        id="6",
        title="Game 6",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/pandemic_legacy_season_1/650787/conversions/pic2452831-thumb.jpg",
    ),
    dict(
        id="7",
        title="Game 7",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/the_mandalorian_adventures/921597/conversions/pic8172090-thumb.jpg",
    ),
    dict(
        id="8",
        title="Game 8",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/pandemic_legacy_season_1/650787/conversions/pic2452831-thumb.jpg",
    ),
    dict(
        id="9",
        title="Game 9",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/the_mandalorian_adventures/921597/conversions/pic8172090-thumb.jpg",
    ),
    dict(
        id="10",
        title="Game 10",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/pandemic_legacy_season_1/650787/conversions/pic2452831-thumb.jpg",
    ),
    dict(
        id="11",
        title="Game 11",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/the_mandalorian_adventures/921597/conversions/pic8172090-thumb.jpg",
    ),
    dict(
        id="12",
        title="Game 12",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/pandemic_legacy_season_1/650787/conversions/pic2452831-thumb.jpg",
    ),
    dict(
        id="13",
        title="Game 13",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/the_mandalorian_adventures/921597/conversions/pic8172090-thumb.jpg",
    ),
    dict(
        id="14",
        title="Game 14",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/pandemic_legacy_season_1/650787/conversions/pic2452831-thumb.jpg",
    ),
    dict(
        id="15",
        title="Game 15",
        description="Description 5",
        min_players=4,
        max_players=10,
        min_ideal_players=5,
        max_ideal_players=8,
        min_play_time=20,
        max_play_time=40,
        rule_time=5,
        complexity="easy",
        min_age=8,
        year=2021,
        video_rules_link="https://www.youtube.com/watch?v=tpxV-uNZef4",
        genres=["other"],
        status="available",
        photo_link="https://nastol.io/storage/games/images/the_mandalorian_adventures/921597/conversions/pic8172090-thumb.jpg",
    ),
]
