import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN") or "INVALID_TOKEN"

# MongoDB
MONGODB_SERVICE_HOST = os.getenv("MONGODB_SERVICE_HOST")
MONGODB_SERVICE_PORT = os.getenv("MONGODB_SERVICE_PORT")
MONGODB_SERVICE_DRIVER = os.getenv("MONGODB_SERVICE_DRIVER")
MONGODB_SERVICE_URL = (
    f"{MONGODB_SERVICE_DRIVER}://{MONGODB_SERVICE_HOST}:{MONGODB_SERVICE_PORT}"
)

# AuthService
AUTH_SERVICE_HOST = os.getenv("AUTH_SERVICE_HOST")
AUTH_SERVICE_PORT = os.getenv("AUTH_SERVICE_PORT")
AUTH_SERVICE_VERSION = os.getenv("AUTH_SERVICE_VERSION")