
games = [
    dict(
        title="Game 1",
        description="Description 1",
        minPlayers=2,
        maxPlayers=6,
        minIdealPlayers=3,
        maxIdealPlayers=6,
        minPlayTime=60,
        maxPlayTime=2 * 60,
        ruleTime=20,
        gameComplexity="hard",
        age=18,
        year=2018,
        gameShortDescription="Short Description 1",
        gameFullDescription="Full Description 1",
        coverImageLink="Link to image 1",
        videoRulesLink="Video Rule Link 1",
        genre="adventure",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 2",
        description="Description 2",
        minPlayers=1,
        maxPlayers=4,
        minIdealPlayers=2,
        maxIdealPlayers=4,
        minPlayTime=30,
        maxPlayTime=90,
        ruleTime=10,
        gameComplexity="medium",
        age=12,
        year=2020,
        gameShortDescription="Short Description 2",
        gameFullDescription="Full Description 2",
        coverImageLink="Link to image 2",
        videoRulesLink="Video Rule Link 2",
        genre="strategy",
        status="available",
        photo_link="resources/static/game_2.jpg",
    ),
    dict(
        title="Game 3",
        description="Description 3",
        minPlayers=3,
        maxPlayers=8,
        minIdealPlayers=4,
        maxIdealPlayers=7,
        minPlayTime=45,
        maxPlayTime=120,
        ruleTime=15,
        gameComplexity="easy",
        age=10,
        year=2019,
        gameShortDescription="Short Description 3",
        gameFullDescription="Full Description 3",
        coverImageLink="Link to image 3",
        videoRulesLink="Video Rule Link 3",
        genre="family",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 4",
        description="Description 4",
        minPlayers=2,
        maxPlayers=5,
        minIdealPlayers=3,
        maxIdealPlayers=5,
        minPlayTime=75,
        maxPlayTime=150,
        ruleTime=25,
        gameComplexity="hard",
        age=16,
        year=2017,
        gameShortDescription="Short Description 4",
        gameFullDescription="Full Description 4",
        coverImageLink="Link to image 4",
        videoRulesLink="Video Rule Link 4",
        genre="horror",
        status="available",
        photo_link="resources/static/game_2.jpg",
    ),
    dict(
        title="Game 5",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 6",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 7",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 8",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 9",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 10",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 11",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 12",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 13",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 14",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        title="Game 15",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="easy",
        age=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
]