version: '3'
services:
  rabbit_mq:
    container_name: rabbit_mq_service
    build: ./rabbit_mq_service
    ports:
      - 5672:5672

  # celery:
  #   build: ./celery_service
  #   container_name: celery_service
    # depends_on:
    #   - rabbit_mq
