import os

SERVICE_SECRET_KEY = os.getenv("SERVICE_SECRET")
SERVICE_SECRET_ALGORITHM = "HS256"
CONFIRMATION_TOKEN_TTL = 60  # sec

MAIL_SERVICE_HOST = os.getenv("MAIL_SERVICE_HOST")
MAIL_SERVICE_PORT = os.getenv("MAIL_SERVICE_PORT")
MAIL_SERVICE_VERSION = os.getenv("MAIL_SERVICE_VERSION")
MAIL_SERVICE_URL = (
    f"http://{MAIL_SERVICE_HOST}:{MAIL_SERVICE_PORT}/api/v{MAIL_SERVICE_VERSION}"
)


REDIS_SERVICE_HOST = os.getenv("REDIS_SERVICE_HOST")
REDIS_SERVICE_PORT = os.getenv("REDIS_SERVICE_PORT")

POSTGRES_SERVICE_HOST = os.getenv("POSTGRES_SERVICE_HOST")
POSTGRES_SERVICE_PORT = os.getenv("POSTGRES_SERVICE_PORT")
POSTGRES_SERVICE_DRIVER = os.getenv("POSTGRES_SERVICE_DRIVER")
POSTGRES_SERVICE_USER = os.getenv("POSTGRES_SERVICE_USER")
POSTGRES_SERVICE_PASSWORD = os.getenv("POSTGRES_SERVICE_PASSWORD")
POSTGRES_SERVICE_NAME = os.getenv("POSTGRES_SERVICE_NAME")
POSTGRES_SERVICE_URL = f"{POSTGRES_SERVICE_DRIVER}://{POSTGRES_SERVICE_USER}:{POSTGRES_SERVICE_PASSWORD}@{POSTGRES_SERVICE_HOST}:{POSTGRES_SERVICE_PORT}/{POSTGRES_SERVICE_NAME}"
