import os

LOG_LEVEL = os.getenv("LOG_LEVEL")

# Postgres service
POSTGRES_SERVICE_HOST = os.getenv("POSTGRES_SERVICE_HOST")
POSTGRES_SERVICE_PORT = os.getenv("POSTGRES_SERVICE_PORT")
POSTGRES_SERVICE_DRIVER = os.getenv("POSTGRES_SERVICE_DRIVER")
POSTGRES_SERVICE_USER = os.getenv("POSTGRES_SERVICE_USER")
POSTGRES_SERVICE_PASSWORD = os.getenv("POSTGRES_SERVICE_PASSWORD")
POSTGRES_SERVICE_NAME = os.getenv("POSTGRES_SERVICE_NAME")
POSTGRES_SERVICE_URL = f"{POSTGRES_SERVICE_DRIVER}://{POSTGRES_SERVICE_USER}:{POSTGRES_SERVICE_PASSWORD}@{POSTGRES_SERVICE_HOST}:{POSTGRES_SERVICE_PORT}/{POSTGRES_SERVICE_NAME}"


# Auth service
AUTH_SERVICE_HOST = os.getenv("AUTH_SERVICE_HOST")
AUTH_SERVICE_PORT = os.getenv("AUTH_SERVICE_PORT")
AUTH_SERVICE_VERSION = os.getenv("AUTH_SERVICE_VERSION")

# Game service
GAME_SERVICE_HOST = os.getenv("GAME_SERVICE_HOST")
GAME_SERVICE_PORT = os.getenv("GAME_SERVICE_PORT")
GAME_SERVICE_VERSION = os.getenv("GAME_SERVICE_VERSION")
