import motor.motor_asyncio
from motor.motor_asyncio import AsyncIOMotorClient as MDB


client = motor.motor_asyncio.AsyncIOMotorClient("mongodb://mongodb_service:27017")
database = client.telegram_db


games = [
    dict(
        id="1",
        gameName="Game 1",
        description="Description 1",
        minPlayers=2,
        maxPlayers=6,
        minIdealPlayers=3,
        maxIdealPlayers=6,
        minPlayTime=60,
        maxPlayTime=2 * 60,
        ruleTime=20,
        gameComplexity="Hard",
        minAge=18,
        year=2018,
        gameShortDescription="Short Description 1",
        gameFullDescription="Full Description 1",
        coverImageLink="Link to image 1",
        videoRulesLink="Video Rule Link 1",
        genre="Adventure",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="2",
        gameName="Game 2",
        description="Description 2",
        minPlayers=1,
        maxPlayers=4,
        minIdealPlayers=2,
        maxIdealPlayers=4,
        minPlayTime=30,
        maxPlayTime=90,
        ruleTime=10,
        gameComplexity="Medium",
        minAge=12,
        year=2020,
        gameShortDescription="Short Description 2",
        gameFullDescription="Full Description 2",
        coverImageLink="Link to image 2",
        videoRulesLink="Video Rule Link 2",
        genre="Strategy",
        status="available",
        photo_link="resources/static/game_2.jpg",
    ),
    dict(
        id="3",
        gameName="Game 3",
        description="Description 3",
        minPlayers=3,
        maxPlayers=8,
        minIdealPlayers=4,
        maxIdealPlayers=7,
        minPlayTime=45,
        maxPlayTime=120,
        ruleTime=15,
        gameComplexity="Easy",
        minAge=10,
        year=2019,
        gameShortDescription="Short Description 3",
        gameFullDescription="Full Description 3",
        coverImageLink="Link to image 3",
        videoRulesLink="Video Rule Link 3",
        genre="Family",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="4",
        gameName="Game 4",
        description="Description 4",
        minPlayers=2,
        maxPlayers=5,
        minIdealPlayers=3,
        maxIdealPlayers=5,
        minPlayTime=75,
        maxPlayTime=150,
        ruleTime=25,
        gameComplexity="Hard",
        minAge=16,
        year=2017,
        gameShortDescription="Short Description 4",
        gameFullDescription="Full Description 4",
        coverImageLink="Link to image 4",
        videoRulesLink="Video Rule Link 4",
        genre="Horror",
        status="available",
        photo_link="resources/static/game_2.jpg",
    ),
    dict(
        id="5",
        gameName="Game 5",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="6",
        gameName="Game 6",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="7",
        gameName="Game 7",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="8",
        gameName="Game 8",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="9",
        gameName="Game 9",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="10",
        gameName="Game 10",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="11",
        gameName="Game 11",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="12",
        gameName="Game 12",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="13",
        gameName="Game 13",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="14",
        gameName="Game 14",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
    dict(
        id="15",
        gameName="Game 15",
        description="Description 5",
        minPlayers=4,
        maxPlayers=10,
        minIdealPlayers=5,
        maxIdealPlayers=8,
        minPlayTime=20,
        maxPlayTime=40,
        ruleTime=5,
        gameComplexity="Easy",
        minAge=8,
        year=2021,
        gameShortDescription="Short Description 5",
        gameFullDescription="Full Description 5",
        coverImageLink="Link to image 5",
        videoRulesLink="Video Rule Link 5",
        genre="Party",
        status="available",
        photo_link="resources/static/game_1.jpg",
    ),
]
