version: '3'

services:
  postgres_service:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_service:/docker-entrypoint-initdb.d
    restart: on-failure
    ports:
      - 5432:5432

  games_service:
    build: ./games_service
    container_name: games_service
    working_dir: /app
    volumes:
      - ./games_service:/app
      - shared_data:/app/shared
    command: bash -c "make"
    environment:
      TZ: "Asia/Novosibirsk"
    env_file: games_service/.env
    restart: on-failure
    ports:
      - 8004:8000

volumes:
  shared_data:
    driver: local