version: '3'
services:
  postgres_service:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    ports:
      - 5432:5432


  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672


  db_service:
    build: ./db_service
    container_name: db_service
    working_dir: /app
    volumes:
      - ./db_service:/app
    command: bash -c "make"
    depends_on:
      - postgres_service
      - rabbitmq
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      TZ: "Asia/Novosibirsk"
    restart: on-failure
    ports:
      - 8001:8000


  telegram_bot_service:
    build: ./telegram_bot_service
    container_name: telegram_bot_service
    working_dir: /app
    depends_on:
      - postgres_service
      - rabbitmq
    volumes:
      - ./telegram_bot_service:/app
      - shared_data:/app/shared
    command: bash -c "make"
    environment:
      TZ: "Asia/Novosibirsk"
    env_file: telegram_bot_service/.env
    restart: on-failure
    ports:
      - 8000:8000

  mongodb_service:
    image: mongo
    container_name: mongodb_service
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: mongodb
      # MONGO_INITDB_ROOT_PASSWORD: mongodb
    restart: on-failure
    ports:
      - 27017:27017

volumes:
  shared_data:
    driver: local