version: '3'
services:
  postgres_service:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure
    ports:
      - 5432:5432

  db_service:
    build: ./db_service
    container_name: db_service
    working_dir: /app
    volumes:
      - ./db_service:/app
    command: bash -c "make"
    depends_on:
      - postgres_service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}
      TZ: ${TIMEZONE}
    restart: on-failure
    ports:
      - 8001:8000

  telegram_bot_service:
    build: ./telegram_bot_service
    container_name: telegram_bot_service
    working_dir: /app
    depends_on:
      - postgres_service
    volumes:
      - ./telegram_bot_service:/app
      - shared_data:/app/shared
    command: bash -c "make"
    environment:
      TZ: ${TIMEZONE}
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DB_API_URL: ${DB_API_URL}
    env_file: telegram_bot_service/.env
    restart: on-failure
    ports:
      - 8000:8000

  mongodb_service:
    image: mongo
    container_name: mongodb_service
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: mongodb
      # MONGO_INITDB_ROOT_PASSWORD: mongodb
    restart: on-failure
    ports:
      - 27017:27017

volumes:
  shared_data:
    driver: local