version: '3'
services:
  postgres_service:
    build: ./postgres_service
    container_name: postgres_service
    env_file: .env
    restart: on-failure
    ports:
      - 5432:5432

  db_service:
    build: ./db_service
    container_name: db_service
    working_dir: /app
    volumes:
      - ./db_service:/app
    command: bash -c "make"
    depends_on:
      - postgres_service
    env_file:
      - .env
      - db_service/.env
    restart: on-failure
    ports:
      - 8001:8000

  telegram_bot_service:
    build: ./telegram_bot_service
    container_name: telegram_bot_service
    working_dir: /app
    depends_on:
      - postgres_service
    volumes:
      - ./telegram_bot_service:/app
      - shared_data:/app/shared
    command: bash -c "make"
    env_file: telegram_bot_service/.env
    restart: on-failure
    ports:
      - 8000:8000

  mongodb_service:
    image: mongo
    container_name: mongodb_service
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: mongodb
      # MONGO_INITDB_ROOT_PASSWORD: mongodb
    restart: on-failure
    ports:
      - 27017:27017

  auth_service:
    build: ./auth_service
    container_name: auth_service
    working_dir: /app
    env_file: 
      - auth_service/.env
      - .env
    volumes:
      - ./auth_service:/app
    command: bash -c "make"
    restart: on-failure
    ports:
      - 8000:8000


volumes:
  shared_data:
    driver: local