version: '3'
services:
  postgres:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    ports:
      - 5432:5432




  # redis_service:
  #   image: redis:6
  #   container_name: redis_service
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - ./redis_service:/data
  #   restart: on-failure
  #   ports:
  #     - 6379:6379

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: on-failure
  #   ports:
  #     - 8080:8080

  telegram_bot_service:
    build: ./telegram_bot_service
    container_name: telegram_bot_service
    working_dir: /app
    volumes:
      - ./telegram_bot_service:/app
    command: bash -c "make"
    environment:
      TZ: "Asia/Novosibirsk"
    restart: on-failure
    ports:
      - 8000:8000
